{
 "title": "ClickHouse",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top remote address",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    remote_addr,\n    count() AS count\nFROM vector.nginx\nGROUP BY remote_addr\nHAVING count > 1000\nORDER BY count DESC;"
    }
   ]
  },
  {
   "title": "Nginx Status Code Count",
   "type": "table",
   "description": "Nginx Status Code Count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    nginx_status,\n    count() AS count\nFROM vector.nginx\nGROUP BY nginx_status\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "Top 5 User Agent",
   "type": "table",
   "description": "Top 5 User Agent",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n    http_user_agent,\n    count() AS count\nFROM vector.nginx\nGROUP BY http_user_agent\nORDER BY count DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top 5 location",
   "type": "table",
   "description": "Top 5 location",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n    request_uri,\n    count() AS count\nFROM vector.nginx\nGROUP BY request_uri\nORDER BY count DESC\nLIMIT 5;\n"
    }
   ]
  }
 ]
}